# https://pre-commit.com
default_install_hook_types: [commit-msg, pre-commit]
default_stages: [pre-commit, manual]
fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: commitizen
        name: commitizen
        entry: uv run cz check
        args: [--commit-msg-file]
        require_serial: true
        language: system
        stages: [commit-msg]

      - id: ruff-check
        name: ruff check
        entry: uv run ruff check --fix
        require_serial: true
        language: system
        types_or: [python, pyi]

      - id: ruff-format
        name: ruff format
        entry: uv run ruff format
        require_serial: true
        language: system
        types_or: [python, pyi]

      - id: mypy
        name: mypy
        entry: uv run mypy src
        pass_filenames: false
        language: system
        types: [python]
